# Generated by Django 5.1.3 on 2025-12-18 04:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник'), ('parent', 'Родитель'), ('student', 'Студент')], default='student', help_text='Роль пользователя в системе', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Телефон контакта', max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to='avatars/')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли пользователь в системе')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=200)),
                ('content', models.TextField(help_text='Содержимое сообщения')),
                ('attachment', models.FileField(blank=True, help_text='Вложение к сообщению (если есть)', null=True, upload_to='message_attachments/')),
                ('is_read', models.BooleanField(default=False, help_text='Прочитано ли сообщение')),
                ('read_at', models.DateTimeField(blank=True, help_text='Время прочтения сообщения', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время отправления')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время последнего изменения')),
                ('recipient', models.ForeignKey(help_text='Получатель сообщения', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='Отправитель сообщения', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('progress', 'Успеваемость'), ('behavior', 'Поведение'), ('absence', 'Пропуски'), ('discipline', 'Дисциплина'), ('achievement', 'Достижения'), ('other', 'Другое')], help_text='Тип отчета', max_length=20)),
                ('title', models.CharField(help_text='Заголовок отчета', max_length=200)),
                ('content', models.TextField(help_text='Содержимое отчета')),
                ('attachment', models.FileField(blank=True, help_text='Документы или доказательства', null=True, upload_to='report_attachments/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', help_text='Статус отчета', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания отчета')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения')),
                ('published_at', models.DateTimeField(blank=True, help_text='Дата публикации отчета', null=True)),
                ('employee', models.ForeignKey(help_text='Сотрудник, создавший отчет', limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='communicati_role_66354b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='communicati_recipie_087104_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='communicati_created_a4ebd4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['employee', 'status'], name='communicati_employe_87b429_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='communicati_created_032bb5_idx'),
        ),
    ]
