# Generated by Django 5.1.3 on 2025-12-29 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название типа родственной связи', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Код типа (например, MOTHER, FATHER, GUARDIAN)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание типа родственной связи', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активен ли тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип родственной связи',
                'verbose_name_plural': 'Типы родственных связей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='Имя родителя/опекуна', max_length=100)),
                ('last_name', models.CharField(db_index=True, help_text='Фамилия родителя/опекуна', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Отчество', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Дата рождения', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], help_text='Гендер', max_length=1, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Основной email', max_length=254)),
                ('phone', models.CharField(help_text='Основной телефон', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, help_text='Дополнительный телефон', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('messenger', models.CharField(blank=True, help_text='Мессенджер (Telegram, WhatsApp, Viber и т.д.)', max_length=50, null=True)),
                ('messenger_id', models.CharField(blank=True, help_text='ID или адрес в выбранном мессенджере', max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='Страна проживания', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='Город/область', max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, help_text='Улица и номер дома', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Почтовый индекс', max_length=20, null=True)),
                ('employer', models.CharField(blank=True, help_text='Место работы', max_length=255, null=True)),
                ('job_position', models.CharField(blank=True, help_text='Должность на месте работы', max_length=100, null=True)),
                ('work_phone', models.CharField(blank=True, help_text='Рабочий телефон', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный'), ('DECEASED', 'Скончался')], db_index=True, default='ACTIVE', help_text='Статус родителя', max_length=20)),
                ('can_receive_notifications', models.BooleanField(default=True, help_text='Может ли получать уведомления')),
                ('preferred_contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Телефон'), ('MESSENGER', 'Мессенджер')], default='EMAIL', help_text='Предпочтительный способ связи', max_length=20)),
                ('consent_gdpr', models.BooleanField(default=False, help_text='Согласие на обработку персональных данных')),
                ('consent_gdpr_date', models.DateTimeField(blank=True, help_text='Дата согласия на обработку данных', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Дата последней активности', null=True)),
            ],
            options={
                'verbose_name': 'Родитель/Опекун',
                'verbose_name_plural': 'Родители/Опекуны',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='parents_par_email_e58cc7_idx'), models.Index(fields=['phone'], name='parents_par_phone_362abe_idx'), models.Index(fields=['status', '-registered_at'], name='parents_par_status_b9310a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True, help_text='ID студента')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Основной контакт для уведомлений')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активна ли связь')),
                ('start_date', models.DateField(auto_now_add=True, help_text='Дата начала опеки')),
                ('end_date', models.DateField(blank=True, help_text='Дата окончания опеки (если применимо)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(help_text='Родитель/опекун', on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to='parents.parent')),
                ('relation_type', models.ForeignKey(help_text='Тип родственной связи', on_delete=django.db.models.deletion.PROTECT, related_name='parent_relations', to='parents.relationtype')),
            ],
            options={
                'verbose_name': 'Связь родителя со студентом',
                'verbose_name_plural': 'Связи родителей со студентами',
                'ordering': ['parent', 'is_primary_contact'],
                'unique_together': {('parent', 'student_id', 'relation_type')},
            },
        ),
    ]
