# Generated by Django 5.1.3 on 2026-02-09 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер обращения')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст обращения')),
                ('consent_pd', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file_content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('file_data', models.BinaryField(blank=True, null=True, verbose_name='Файл (данные)')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, verbose_name='Кратко')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
