# Generated by Django 5.1.3 on 2025-12-29 20:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название квалификации', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Код квалификации', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('DEGREE', 'Учёная степень'), ('CERTIFICATE', 'Сертификат'), ('COURSE', 'Курс повышения квалификации'), ('LICENSE', 'Лицензия'), ('SKILL', 'Профессиональный навык')], db_index=True, help_text='Тип квалификации', max_length=20)),
                ('issuing_organization', models.CharField(blank=True, help_text='Организация-издатель', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Обязательна ли для определённых должностей')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Полное название отделения/факультета', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Код отделения (например, ИС-01)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание функций и ответственности отделения', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email отделения для координации', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Телефон отделения', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('office_location', models.CharField(blank=True, help_text='Местоположение офиса', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активно ли отделение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_department', models.ForeignKey(blank=True, help_text='Родительское отделение (для иерархии)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartments', to='employees.department')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text='Имя сотрудника', max_length=100)),
                ('last_name', models.CharField(db_index=True, help_text='Фамилия сотрудника', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Отчество', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Дата рождения', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], help_text='Пол', max_length=1, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Корпоративный email', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Основной телефон', max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('mobile_phone', models.CharField(blank=True, help_text='Мобильный телефон', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')])),
                ('employee_id', models.CharField(db_index=True, help_text='Табельный номер', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('ON_LEAVE', 'В отпуске'), ('SUSPENDED', 'Приостановлен'), ('DISMISSED', 'Уволен')], db_index=True, default='ACTIVE', help_text='Статус сотрудника', max_length=20)),
                ('hire_date', models.DateField(auto_now_add=True, help_text='Дата найма')),
                ('termination_date', models.DateField(blank=True, help_text='Дата увольнения', null=True)),
                ('office_room', models.CharField(blank=True, help_text='Номер кабинета/офиса', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Фотография сотрудника', null=True, upload_to='employee_photos/')),
                ('biography', models.TextField(blank=True, help_text='Биография и достижения', null=True)),
                ('is_contact_person', models.BooleanField(default=False, help_text='Может ли быть контактным лицом для родителей')),
                ('can_send_notifications', models.BooleanField(default=True, help_text='Может ли отправлять уведомления родителям')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Отделение', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Руководитель отделения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(default='09:00', help_text='Начало работы в пн')),
                ('monday_end', models.TimeField(default='18:00', help_text='Конец работы в пн')),
                ('tuesday_start', models.TimeField(default='09:00')),
                ('tuesday_end', models.TimeField(default='18:00')),
                ('wednesday_start', models.TimeField(default='09:00')),
                ('wednesday_end', models.TimeField(default='18:00')),
                ('thursday_start', models.TimeField(default='09:00')),
                ('thursday_end', models.TimeField(default='18:00')),
                ('friday_start', models.TimeField(default='09:00')),
                ('friday_end', models.TimeField(default='18:00')),
                ('saturday_start', models.TimeField(blank=True, default='10:00', null=True)),
                ('saturday_end', models.TimeField(blank=True, default='14:00', null=True)),
                ('sunday_start', models.TimeField(blank=True, null=True)),
                ('sunday_end', models.TimeField(blank=True, null=True)),
                ('consultation_hours', models.CharField(blank=True, help_text='Время консультаций с родителями (например, пн-чт 16:00-18:00)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(help_text='Сотрудник', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Расписание сотрудника',
                'verbose_name_plural': 'Расписания сотрудников',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название должности', max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Код должности (например, TEACH-001)', max_length=50, unique=True)),
                ('department_category', models.CharField(db_index=True, help_text='Категория (Педагогический, Административный, Технический)', max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Стажер'), (2, 'Специалист'), (3, 'Старший специалист'), (4, 'Руководитель'), (5, 'Директор')], help_text='Уровень ответственности')),
                ('description', models.TextField(blank=True, help_text='Описание обязанностей и требований', null=True)),
                ('required_education', models.CharField(blank=True, help_text='Требуемое образование', max_length=255, null=True)),
                ('required_experience_years', models.IntegerField(default=0, help_text='Требуемый опыт работы в годах')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная зарплата', max_digits=10, null=True)),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная зарплата', max_digits=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активна ли должность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['code', '-is_active'], name='employees_p_code_ba5bbe_idx'), models.Index(fields=['department_category', 'level'], name='employees_p_departm_997b90_idx')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Должность', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, help_text='Квалификации и сертификаты', related_name='employees', to='employees.qualification'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code', '-is_active'], name='employees_d_code_eb1e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='employees_d_name_54c2ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('code', 'name')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id', '-status'], name='employees_e_employe_4f6504_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position', 'status'], name='employees_e_positio_440f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', '-hire_date'], name='employees_e_departm_5ffed0_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('hire_date__lte', datetime.date(2025, 12, 29))), name='hire_date_not_future'),
        ),
    ]
