# Generated by Django 5.1.3 on 2026-03-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_hire_date_not_future_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='hire_date_not_future',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Дата найма', null=True),
        ),
    ]
